### PR TITLE
Minor bug fixes

### LINKED ISSUE #243: Add to UG that "clear" is an undoable command

### LINKED ISSUE #255: Add mark commands to help window
markT and markD

### PR DESCRIPTION
**Pull request by samuelfangjw**
Add markT and markD to help panel, closes #255,
Fix bug where clicking on project does not show feedback to user.
Update ug with details on undoable commands closes #243

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/RedoCommand.java [hunk 1]
```diff
@@ -14,7 +14,7 @@
 public class RedoCommand extends Command {
 
     public static final String COMMAND_WORD = "redo";
-    public static final String MESSAGE_SUCCESS = "Redo success! %s";
+    public static final String MESSAGE_SUCCESS = "Redo success!\n%s";
```
Comment (lirc572) [inline src/main/java/seedu/address/logic/commands/RedoCommand.java]: Perhaps successful or succeeded?

File: src/main/java/seedu/address/logic/commands/UndoCommand.java [hunk 2]
```diff
@@ -15,7 +15,7 @@
 public class UndoCommand extends Command {
 
     public static final String COMMAND_WORD = "undo";
-    public static final String MESSAGE_SUCCESS = "Undo success! %s";
+    public static final String MESSAGE_SUCCESS = "Undo success!\n%s";
```
Comment (lirc572) [inline src/main/java/seedu/address/logic/commands/UndoCommand.java]: here also

**Review by lirc572 — COMMENTED** [review]
Two minor comments

File: src/main/java/seedu/address/logic/commands/RedoCommand.java (hunk 1 above)
Comment (samuelfangjw) [reply src/main/java/seedu/address/logic/commands/RedoCommand.java]: Changed

File: src/main/java/seedu/address/logic/commands/ViewContactsCommand.java [hunk 3]
```diff
@@ -13,7 +13,7 @@
 
     public static final String COMMAND_WORD = "contacts";
 
-    public static final String MESSAGE_SUCCESS = "Viewing all Contacts.";
+    public static final String MESSAGE_SUCCESS = "Viewing All Contacts.";
```
Comment (lirc572) [inline src/main/java/seedu/address/logic/commands/ViewContactsCommand.java:16]: It seems that other commands' MESSAGE_SUCCESS do not capitalize all words

Comment (samuelfangjw) [reply src/main/java/seedu/address/logic/commands/ViewContactsCommand.java:16]: This is consistent with the other view commands, changed because it looks better next to those. If we want to revert maybe someone can take another look and change it for all.

Comment (lirc572) [reply src/main/java/seedu/address/logic/commands/ViewContactsCommand.java:16]: Ohh okay sure! Then I think can leave it like this!

**Review by lirc572 — APPROVED** [review]
